root = input("Shopping Cart helps to calculate quantity and price of five different food! Press Enter to continue...")
food = input("What do you like to buy today:")
food1 = input("Do you want to buy second food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food2 = input("Do you want to buy third food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food3 = input("Do you want to buy fourth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food4 = input("Do you want to buy fifth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
quantity = float(input("Enter the quantity of first food: "))
quantity1 = float(input("Enter the quantity of second food. If doesn't select the second food, Press 0 to continue..."))
quantity2 = float(input("Enter the quantity of third food: If doesn't select the third food, Press 0 to continue..."))
quantity3 = float(input("Enter the quantity of fourth food: If doesn't select the fourth food, Press 0 to continue..."))
quantity4 = float(input("Enter the price of fifth food: If doesn't select the fifth food, Press 0 to continue..."))
price = float(input("Enter the price of first food: "))
price1 = float(input("Enter the price of second food: If doesn't select the second food, Press 0 to continue..."))
price2 = float(input("Enter the price of third food: If doesn't select the third food, Press 0 to continue..."))
price3 = float(input("Enter the price of fourth food: If doesn't select the fourth food, Press 0 to continue..."))
price4 = float(input("Enter the price of fifth food: If doesn't select the fifth food, Press 0 to continue..."))
print(f"You have bought {round(quantity)} x {food}'s, {round(quantity1)} x {food1}'s {round(quantity2)} x {food2}'s, {round(quantity3)} x {food3}, {round(quantity4)} x {food4}'s! ")
total = price * quantity + price1 * quantity1 + price2 * quantity2 + price3 * quantity3 + price4 * quantity4
print(f"The total is: {total} lei.")
root = input("For any questions about this program and report bugs, contact me at vioit@hotmail.com to more information or solve the problem! Developed by Vio IT Press Enter to exit...")