root = input("Shopping Cart helps to calculate quantity and price of five different food! Press Enter to continue...")
food = input("What do you like to buy today:")
food1 = input("Do you want to buy second food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food2 = input("Do you want to buy third food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food3 = input("Do you want to buy fourth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food4 = input("Do you want to buy fifth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food5 = input("Do you want to buy sixth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food6 = input("Do you want to buy seventh food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food7 = input("Do you want to buy eighth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food8 = input("Do you want to buy nineth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
food9 = input("Do you want to buy tenth food? If Yes, Enter the name food directly or if No, Press Enter to continue...")
quantity = float(input("Enter the quantity of first food: "))
quantity1 = float(input("Enter the quantity of second food. If doesn't select the second food, Press 0 to continue..."))
quantity2 = float(input("Enter the quantity of third food: If doesn't select the third food, Press 0 to continue..."))
quantity3 = float(input("Enter the quantity of fourth food: If doesn't select the fourth food, Press 0 to continue..."))
quantity4 = float(input("Enter the price of fifth food: If doesn't select the fifth food, Press 0 to continue..."))
quantity5 = float(input("Enter the price of sixth food: If doesn't select the sixth food, Press 0 to continue..."))
quantity6 = float(input("Enter the price of seventh food: If doesn't select the seventh food, Press 0 to continue..."))
quantity7 = float(input("Enter the price of eighth food: If doesn't select the eighth food, Press 0 to continue..."))
quantity8 = float(input("Enter the price of nineth food: If doesn't select the nineth food, Press 0 to continue..."))
quantity9 = float(input("Enter the price of tenth food: If doesn't select the tenth food, Press 0 to continue..."))
price = float(input("Enter the price of first food: "))
price1 = float(input("Enter the price of second food: If doesn't select the second food, Press 0 to continue..."))
price2 = float(input("Enter the price of third food: If doesn't select the third food, Press 0 to continue..."))
price3 = float(input("Enter the price of fourth food: If doesn't select the fourth food, Press 0 to continue..."))
price4 = float(input("Enter the price of fifth food: If doesn't select the fifth food, Press 0 to continue..."))
price5 = float(input("Enter the price of sixth food: If doesn't select the sixth food, Press 0 to continue..."))
price6 = float(input("Enter the price of seventh food: If doesn't select the seventh food, Press 0 to continue..."))
price7 = float(input("Enter the price of eighth food: If doesn't select the eighth food, Press 0 to continue..."))
price8 = float(input("Enter the price of nineth food: If doesn't select the nineth food, Press 0 to continue..."))
price9 = float(input("Enter the price of tenth food: If doesn't select the tenth food, Press 0 to continue..."))
print(f"You have bought {round(quantity)} x {food}'s, {round(quantity1)} x {food1}'s, {round(quantity2)} x {food2}'s, {round(quantity3)} x {food3}'s,{round(quantity4)} x {food4}'s, {round(quantity5)} x {food5}'s, {round(quantity6)} x {food6}'s, {round(quantity7)} x {food7}'s, {round(quantity8)} x {food8}'s, {round(quantity9)} x {food9}'s !")
total = price * quantity + price1 * quantity1 + price2 * quantity2 + price3 * quantity3 + price4 * quantity4 + price5 * quantity5 
+ price6 * quantity6 + price7 * quantity7 + price8 * quantity8 + price9 * quantity9
print(f"The total is: {total} lei.")
root = input("For any questions about this program and report bugs, contact me at vioit@hotmail.com to more information or solve the problem! Developed by Vio IT Press Enter to exit...")